import { Profile, Trip, TripSwipe, TripReview } from './types';

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'user-aarav',
    full_name: 'Aarav Sharma',
    bio: 'Mountain addict, amateur drone pilot & chai lover. 8 high-altitude treks completed across Himachal & Ladakh. Strict believer in splitting every ₹ fairly!',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    age: 25,
    travel_style: 'Trekker',
    budget_tier: 'Budget',
    vibe_score: 4.9,
    reviews_count: 14,
    badges: {
      Punctual: 12,
      Chill: 14,
      'Budget Maestro': 10,
      Photographer: 11,
      'Navigation Pro': 9,
    },
  },
  {
    id: 'user-rhea',
    full_name: 'Rhea Chakraborty',
    bio: 'Solo backpacker turned group organizer. Obsessed with cliff sunsets, indie cafes, and discovering offbeat coastal trails.',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    age: 24,
    travel_style: 'Backpacker',
    budget_tier: 'Budget',
    vibe_score: 4.8,
    reviews_count: 19,
    badges: {
      Chill: 18,
      'Budget Maestro': 16,
      'Party Starter': 14,
      Photographer: 12,
    },
  },
  {
    id: 'user-kabir',
    full_name: 'Kabir Sen',
    bio: 'Digital nomad building products from beach cafes & mountain co-working spaces. Surfing enthusiast and night owl.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    age: 28,
    travel_style: 'Digital Nomad',
    budget_tier: 'Mid-range',
    vibe_score: 4.6,
    reviews_count: 8,
    badges: {
      Punctual: 7,
      Chill: 8,
      'Navigation Pro': 6,
    },
  },
  {
    id: 'user-ananya',
    full_name: 'Ananya Mehta',
    bio: 'Architect passionate about ancient stone temples, scenic homestays, and aesthetic cafes. Reliable planner with an eye for detail.',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    age: 26,
    travel_style: 'Leisure',
    budget_tier: 'Mid-range',
    vibe_score: 4.95,
    reviews_count: 11,
    badges: {
      Photographer: 10,
      Punctual: 9,
      Chill: 11,
      'Budget Maestro': 8,
      'Safety First': 6,
    },
  },
  {
    id: 'user-dev',
    full_name: 'Dev Malhotra',
    bio: 'Roadtripper who knows every mountain hairpin bend from Manali to Leh. Carries toolkits, first aid, and the ultimate road trip playlist.',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    age: 27,
    travel_style: 'Roadtripper',
    budget_tier: 'Budget',
    vibe_score: 4.7,
    reviews_count: 16,
    badges: {
      'Navigation Pro': 15,
      'Budget Maestro': 14,
      Punctual: 12,
      Chill: 13,
      'Party Starter': 9,
    },
  },
  {
    id: 'user-tanvi',
    full_name: 'Tanvi Verma',
    bio: 'Food anthropologist and yoga practitioner. Always hunting down the best momos and quiet sunrise meditation spots.',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    age: 25,
    travel_style: 'Backpacker',
    budget_tier: 'Budget',
    vibe_score: 4.85,
    reviews_count: 9,
    badges: {
      Chill: 9,
      'Culinary Explorer': 8,
      Punctual: 7,
    },
  },
];

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip-kasol',
    host_id: 'user-aarav',
    title: 'Kasol & Kheerganga Stargazing Backpacking',
    destination: 'Parvati Valley, Himachal Pradesh',
    description:
      'A 5-day budget backpacking trip through Parvati Valley! We will stay in authentic wooden hostels in Kasol & Tosh, hike through cedar forests to Kheerganga natural hot sulfur springs, camp under the Milky Way, and split transport and cafe expenses evenly.',
    cover_image:
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
    budget_per_person: 6500,
    total_budget: 26000,
    start_date: '2026-10-15',
    end_date: '2026-10-20',
    max_members: 4,
    min_vibe_score: 4.2,
    travel_style: 'Backpacker',
    status: 'open',
    itinerary_highlights: [
      'Wooden hostel stay in Tosh village with glacier views',
      'Kheerganga summit hike & stargazing at natural thermal bath',
      'Cafe hopping in Old Kasol for Israeli food & river jams',
      'Chalal pine forest hike along the gushing Parvati river',
    ],
    members: [
      {
        id: 'tm-1',
        trip_id: 'trip-kasol',
        user_id: 'user-aarav',
        role: 'host',
        joined_at: '2026-09-20T10:00:00Z',
        profile: MOCK_PROFILES[0],
      },
      {
        id: 'tm-2',
        trip_id: 'trip-kasol',
        user_id: 'user-ananya',
        role: 'member',
        joined_at: '2026-09-22T14:30:00Z',
        profile: MOCK_PROFILES[3],
      },
    ],
  },
  {
    id: 'trip-gokarna',
    host_id: 'user-rhea',
    title: 'Gokarna 5-Beach Cliff Trek & Coastal Shack Camping',
    destination: 'Gokarna, Karnataka',
    description:
      'Skip crowded commercial party beaches! Join us to trek along the dramatic cliffs connecting Kudle, Om, Half Moon, and Paradise Beach. We will rent scooties to explore Yana limestone caves, kayak in secret lagoons, and camp beachside under the stars.',
    cover_image:
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    budget_per_person: 4800,
    total_budget: 24000,
    start_date: '2026-10-24',
    end_date: '2026-10-28',
    max_members: 5,
    min_vibe_score: 4.0,
    travel_style: 'Trekker',
    status: 'open',
    itinerary_highlights: [
      'Coastal cliff trail hike connecting 5 secluded beaches',
      'Beach shack bonfire & acoustic guitar sunset session',
      'Yana Rock karst formations & Vibhooti waterfall swim',
      'Bioluminescent plankton spotting boat ride at night',
    ],
    members: [
      {
        id: 'tm-3',
        trip_id: 'trip-gokarna',
        user_id: 'user-rhea',
        role: 'host',
        joined_at: '2026-09-21T09:00:00Z',
        profile: MOCK_PROFILES[1],
      },
      {
        id: 'tm-4',
        trip_id: 'trip-gokarna',
        user_id: 'user-kabir',
        role: 'member',
        joined_at: '2026-09-23T11:00:00Z',
        profile: MOCK_PROFILES[2],
      },
      {
        id: 'tm-5',
        trip_id: 'trip-gokarna',
        user_id: 'user-dev',
        role: 'member',
        joined_at: '2026-09-24T18:00:00Z',
        profile: MOCK_PROFILES[4],
      },
    ],
  },
  {
    id: 'trip-spiti',
    host_id: 'user-ananya',
    title: 'Spiti Valley Autumn Whiteout & Monasteries 4x4 Expedition',
    destination: 'Spiti Valley, Himachal Pradesh',
    description:
      'An epic 8-day high-altitude overland journey through Kinnaur and Spiti. We will explore Key Monastery, send postcards from the highest post office in the world at Hikkim (4,400m), stay in heated Spitian mud homestays, and chase reflections at Chandratal.',
    cover_image:
      'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80',
    budget_per_person: 18500,
    total_budget: 111000,
    start_date: '2026-11-05',
    end_date: '2026-11-13',
    max_members: 6,
    min_vibe_score: 4.5,
    travel_style: 'Roadtripper',
    status: 'open',
    itinerary_highlights: [
      'Key Gompa thousand-year Buddhist monastery blessing',
      'Hikkim world’s highest post office & Komik highest village',
      '4x4 rugged pass crossings through Kunzum Pass',
      'Camping near the crescent shores of Chandratal Lake',
    ],
    members: [
      {
        id: 'tm-6',
        trip_id: 'trip-spiti',
        user_id: 'user-ananya',
        role: 'host',
        joined_at: '2026-09-15T12:00:00Z',
        profile: MOCK_PROFILES[3],
      },
      {
        id: 'tm-7',
        trip_id: 'trip-spiti',
        user_id: 'user-aarav',
        role: 'member',
        joined_at: '2026-09-18T16:00:00Z',
        profile: MOCK_PROFILES[0],
      },
    ],
  },
  {
    id: 'trip-meghalaya',
    host_id: 'user-dev',
    title: 'Meghalaya Double Decker Bridges & Crystal Umngot Kayaking',
    destination: 'Cherrapunji & Dawki, Meghalaya',
    description:
      'Descend 3,500 mossy steps down into the dense rainforest of Nongriat to stand on the centuries-old Jingkieng Nongriat double-decker living root bridge. Kayak on the crystal-clear glass waters of Dawki and explore underground limestone caves.',
    cover_image:
      'https://images.unsplash.com/photo-1608755728617-aefab37d2edd?auto=format&fit=crop&w=1200&q=80',
    budget_per_person: 11500,
    total_budget: 46000,
    start_date: '2026-11-20',
    end_date: '2026-11-26',
    max_members: 4,
    min_vibe_score: 4.3,
    travel_style: 'Trekker',
    status: 'open',
    itinerary_highlights: [
      'Double Decker Living Root Bridge hike & rainbow falls swim',
      'Transparent river kayaking at Indo-Bangla border in Dawki',
      'Mawsmai & Arwah limestone spelunking and fossil exploration',
      'Bamboo trail trek along the cliff edge of Mawryngkhang',
    ],
    members: [
      {
        id: 'tm-8',
        trip_id: 'trip-meghalaya',
        user_id: 'user-dev',
        role: 'host',
        joined_at: '2026-09-19T10:00:00Z',
        profile: MOCK_PROFILES[4],
      },
      {
        id: 'tm-9',
        trip_id: 'trip-meghalaya',
        user_id: 'user-tanvi',
        role: 'member',
        joined_at: '2026-09-25T14:00:00Z',
        profile: MOCK_PROFILES[5],
      },
    ],
  },
  {
    id: 'trip-kerala',
    host_id: 'user-kabir',
    title: 'Varkala Cliff Workation & Munroe Island Canoe Trails',
    destination: 'Varkala & Munroe Island, Kerala',
    description:
      'Combine productive remote work with surfing, yoga on the red cliffs, and peaceful wooden canoe rides through the mangrove canals of Munroe Island. Shared beach villa with high-speed fiber internet.',
    cover_image:
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
    budget_per_person: 8900,
    total_budget: 35600,
    start_date: '2026-12-01',
    end_date: '2026-12-07',
    max_members: 4,
    min_vibe_score: 4.4,
    travel_style: 'Digital Nomad',
    status: 'open',
    itinerary_highlights: [
      'Red cliff oceanfront cafe co-working setup',
      'Morning surf lessons at Black Beach',
      'Traditional hand-paddled Munroe Island mangrove canal safari',
      'Authentic Kerala Sadhya feast & Ayurvedic rejuvenation',
    ],
    members: [
      {
        id: 'tm-10',
        trip_id: 'trip-kerala',
        user_id: 'user-kabir',
        role: 'host',
        joined_at: '2026-09-20T10:00:00Z',
        profile: MOCK_PROFILES[2],
      },
    ],
  },
];

export const MOCK_SWIPES: TripSwipe[] = [
  {
    id: 'swipe-1',
    trip_id: 'trip-kasol',
    user_id: 'user-dev',
    swipe_direction: 'like',
    status: 'pending',
    created_at: '2026-09-28T10:20:00Z',
    user: MOCK_PROFILES[4],
    trip: MOCK_TRIPS[0],
  },
  {
    id: 'swipe-2',
    trip_id: 'trip-kasol',
    user_id: 'user-tanvi',
    swipe_direction: 'like',
    status: 'pending',
    created_at: '2026-09-29T14:10:00Z',
    user: MOCK_PROFILES[5],
    trip: MOCK_TRIPS[0],
  },
  {
    id: 'swipe-3',
    trip_id: 'trip-gokarna',
    user_id: 'user-aarav',
    swipe_direction: 'like',
    status: 'pending',
    created_at: '2026-09-29T16:45:00Z',
    user: MOCK_PROFILES[0],
    trip: MOCK_TRIPS[1],
  },
  {
    id: 'swipe-4',
    trip_id: 'trip-spiti',
    user_id: 'user-rhea',
    swipe_direction: 'like',
    status: 'pending',
    created_at: '2026-09-30T08:30:00Z',
    user: MOCK_PROFILES[1],
    trip: MOCK_TRIPS[2],
  },
];

export const MOCK_REVIEWS: TripReview[] = [
  {
    id: 'rev-1',
    trip_id: 'trip-kasol',
    reviewer_id: 'user-aarav',
    reviewee_id: 'user-ananya',
    rating: 5,
    tags: ['Punctual', 'Chill', 'Photographer'],
    comment:
      'Ananya was an absolute joy to travel with! She woke up on time for every early alpine trek, took breathtaking portraits of the whole squad, and stayed super calm during the sudden rainstorm.',
    created_at: '2026-09-10T11:00:00Z',
    reviewer: MOCK_PROFILES[0],
    reviewee: MOCK_PROFILES[3],
  },
  {
    id: 'rev-2',
    trip_id: 'trip-kasol',
    reviewer_id: 'user-ananya',
    reviewee_id: 'user-aarav',
    rating: 5,
    tags: ['Budget Maestro', 'Navigation Pro', 'Chill'],
    comment:
      'Aarav is a master trip lead. He managed the shared UPI group kitty seamlessly down to the last rupee, and his offline trail maps saved us when our phone signals died at 3,000 meters.',
    created_at: '2026-09-10T12:00:00Z',
    reviewer: MOCK_PROFILES[3],
    reviewee: MOCK_PROFILES[0],
  },
  {
    id: 'rev-3',
    trip_id: 'trip-gokarna',
    reviewer_id: 'user-rhea',
    reviewee_id: 'user-dev',
    rating: 5,
    tags: ['Navigation Pro', 'Party Starter', 'Punctual'],
    comment:
      'Dev drove our squad safely through foggy ghat passes, brought an acoustic guitar for the beach bonfire, and made sure everyone felt included throughout the trip!',
    created_at: '2026-09-12T15:00:00Z',
    reviewer: MOCK_PROFILES[1],
    reviewee: MOCK_PROFILES[4],
  },
];
